spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/Development/h2/databases/spring_db2
    username: sa
    password:

logging:
  level:
    org:
      springframework:
        jdbc: debug